version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - ./docker/volumes/mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./docker/volumes/wordpress_data:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  scratch:
    env_file: .env
    image: 'scratch'
    volumes:
      - ./:ABS_PATH